name: commit
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - run: echo Getting ready to send data to the webhook
      - name: Send data to the webhook
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ github.actor }}:${{ github.event.head_commit.message }}:${{ github.repository }}:${{ github.event.head_commit.url }}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}